#!/usr/bin/env bash

##########################################################################################
# file-change-monitor.sh                                                                 #
# Bash script that watches a directory and reports create / modify / delete events live. #
# Can install itself as a systemd service (--install-service).                           #
# Supports optional Checkmk and Grafana alert integration.                               #
# Includes email-based alerts when ALERT_EMAIL is configured.                            #
# Author: Filcu Alexandru                                                                #
##########################################################################################

set -euo pipefail

readonly VERSION="0.1"
DRY_RUN=0

######################################################################
# Watch configuration (WATCH_DIR can be overridden via environment). #
#   - WATCH_DIR    : directory to watch.                             #
#   - EVENTS       : inotify events to react to.                     #
#   - SERVICE_PATH : where --install-service writes the unit.        #
######################################################################

WATCH_DIR="${WATCH_DIR:-/path/to/directory}"
EVENTS=("create" "modify" "delete")
SERVICE_PATH="${SERVICE_PATH:-/etc/systemd/system/file-change-monitor.service}"

################################################################################
# E-Mail alert configuration.                                                  #
#   - Set: ALERT_EMAIL to enable email notifications (fired on delete events). #
#   - Example: ALERT_EMAIL="ops@example.com" ./file-change-monitor.sh          #
################################################################################

ALERT_EMAIL="${ALERT_EMAIL:-}"

# Use colors only when writing to a terminal: green=create, yellow=modify, red=delete.
if [[ -t 1 ]]; then
    GREEN=$'\e[32m'; YELLOW=$'\e[33m'; RED=$'\e[31m'; RST=$'\e[0m'
else
    GREEN=""; YELLOW=""; RED=""; RST=""
fi

usage() {
    cat <<USAGE
Usage: ${0##*/} [--dry-run] [--print-unit] [--install-service] [--version] [--help]

Watch WATCH_DIR and print create/modify/delete events as they happen.
Runs continuously until interrupted (Ctrl-C). Email alerts fire on delete events.

Options:
  --dry-run          Watch and print events, but preview alerts instead of sending
  --print-unit       Print a systemd unit file to stdout
  --install-service  Write the unit to SERVICE_PATH and reload systemd
  --version          Show version and exit
  --help             Show this help and exit

Email: set ALERT_EMAIL (in the script or via environment) to enable.
       Requires a working 'mail' command and a configured MTA/relay.
USAGE
}

die() { echo "Error: $*" >&2; exit 1; }

# Print a systemd unit for this script, using its real path and current config.
unit_file() {
    local self
    self=$(readlink -f -- "$0")
    cat <<UNIT
# Generated by ${0##*/} ${VERSION}
[Unit]
Description=File change monitor (inotify) for a watched directory
After=local-fs.target

[Service]
Type=simple
Environment=WATCH_DIR=${WATCH_DIR}
UNIT
    [[ -n "$ALERT_EMAIL" ]] && echo "Environment=ALERT_EMAIL=${ALERT_EMAIL}"
    cat <<UNIT
ExecStart=${self}
Restart=on-failure
RestartSec=5
User=root
NoNewPrivileges=true
ProtectSystem=full
ProtectHome=read-only
PrivateTmp=true

[Install]
WantedBy=multi-user.target
UNIT
}

# Write the unit to SERVICE_PATH and reload systemd. Writing is the permission
# check: if it fails, point the user at sudo / --print-unit.
install_service() {
    if ! unit_file > "$SERVICE_PATH" 2>/dev/null; then
        die "could not write ${SERVICE_PATH} (try sudo, or: ${0##*/} --print-unit | sudo tee ${SERVICE_PATH})"
    fi
    echo "Installed: ${SERVICE_PATH}"
    if command -v systemctl >/dev/null 2>&1; then
        systemctl daemon-reload 2>/dev/null || true
    fi
    echo "Enable and start it with: systemctl enable --now ${SERVICE_PATH##*/}"
}

# Emit console alerts and optionally send email when ALERT_EMAIL is configured.
# Designed as an integration point for external monitoring systems (Checkmk, Grafana, etc.).
alert() {
    local detail="$*"
    local body="File event on $(hostname): ${detail}"

    if (( DRY_RUN )); then
        echo "[dry-run] would raise alert: ${detail}"
        [[ -n "$ALERT_EMAIL" ]] && echo "[dry-run] would email: ${ALERT_EMAIL}"
        return 0
    fi

    echo "ALERT: ${body}" >&2

    if [[ -n "$ALERT_EMAIL" ]]; then
        if command -v mail >/dev/null 2>&1; then
            echo "$body" | mail -s "File alert on $(hostname)" "$ALERT_EMAIL"
        else
            echo "Warning: ALERT_EMAIL is set but 'mail' command was not found" >&2
        fi
    fi
}

# Parse arguments.
while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry-run)         DRY_RUN=1; shift ;;
        --print-unit)      unit_file; exit 0 ;;
        --install-service) install_service; exit 0 ;;
        --version)         echo "Version=${VERSION}"; exit 0 ;;
        --help)            usage; exit 0 ;;
        *)                 die "unknown option: $1" ;;
    esac
done

# Sanity checks.
command -v inotifywait >/dev/null 2>&1 || die "inotifywait not found (install inotify-tools)"
[[ -d "$WATCH_DIR" ]]                  || die "watch directory not found: $WATCH_DIR"
(( ${#EVENTS[@]} > 0 ))                || die "no events configured in EVENTS"

# Build the -e arguments for inotifywait from the EVENTS array.
event_args=()
for e in "${EVENTS[@]}"; do event_args+=(-e "$e"); done

echo "Watching ${WATCH_DIR} for: ${EVENTS[*]} (Ctrl-C to stop)"

# -m: keep running; -q: quiet startup; --format/--timefmt: clean, parseable lines.
inotifywait -m -q "$WATCH_DIR" "${event_args[@]}" \
        --timefmt '%F %H:%M:%S' --format '%T %e %w%f' |
while read -r day time event file; do
    case "$event" in
        *DELETE*) color=$RED ;;
        *CREATE*) color=$GREEN ;;
        *MODIFY*) color=$YELLOW ;;
        *)        color=$RST ;;
    esac
    printf '%b[%s %s] %-8s %s%b\n' "$color" "$day" "$time" "$event" "$file" "$RST"

    # Alert (and email) only on deletions; widen this case to alert on more events.
    case "$event" in
        *DELETE*) alert "deleted: $file" ;;
    esac
done